### ISSUE TITLE
Your plugin submission

### ISSUE THREAD

**Issue by orthagh** [akm77/ldapcomputers#1]
Hello.

I received yestersday, your submission for adding this GLPI plugin (ldapcomputers) to https://plugins.glpi-project.org.

Before i accept your request, here is a list of things you need to correct in your xml:

- please fill correctly the list of url: https://github.com/pluginsGLPI/ldapcomputers doesn't exist
- add a logo
- and optionnaly some screenshots.

Regards

**Comment by akm77** [comment]
Hello.

All items in this issue was fixed.
Please, check it again

Regards.

**Comment by orthagh** [comment]
Thank you.

Your plugin has been approved:
https://plugins.glpi-project.org/#/plugin/ldapcomputers

Regards
